version: "3.4"

networks:
  eventarea:

services:
  identity.api:
    image: identityapi
    container_name: identityapi-container
    build:
      context: .
      args:
        - GIT_TOKEN=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
      dockerfile: MicroServicesDocker\Dockerfile_Identity
    ports:
      - 7160:80
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=Identity
      - DB_SA_PASSWORD=password@12345#
    networks:
      - eventarea

  apigateway:
    image: apigateway
    container_name: apigateway-container
    build:
      context: .
      args:
        - GIT_TOKEN=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
      dockerfile: MicroServicesDocker\Dockerfile_Gateway
    ports:
      - 7094:80
    networks:
      - eventarea

  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - eventarea
