FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
# Defining args for reading from docker-compose file
ARG GIT_TOKEN
# Defining environment variables
ENV PROJECT_NAME EventAreaMicroservices
ENV GIT_TOKEN "$GIT_TOKEN"
ENV GIT_DOMAIN github.com
ENV GIT_PROJECT_PATH ShukaQA/$PROJECT_NAME.git
ENV GIT_REPO=https://$GIT_TOKEN@$GIT_DOMAIN/$GIT_PROJECT_PATH

# Creating working directory
WORKDIR /src
# Cloning project repository
RUN git clone $GIT_REPO

WORKDIR "/src/EventAreaMicroservices/Event.API"
RUN dotnet restore "Event.API.csproj"

WORKDIR "/src/EventAreaMicroservices/Event.API"
RUN dotnet build "Event.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Event.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Event.API.dll"]